apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-db
  name: ashu-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-db
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        env: # to pass env vairable and its vaules 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: # reading value from somewhere 
            secretKeyRef: # reading from secret 
              key: ashudbpass # key 
              name: ashu-db-password # name of secret  
        - name: MYSQL_DATABASE
          valueFrom: # using to fetch 
            configMapKeyRef:
              key: dbname # key of cm 
              name: ashu-cm1 # name of cm 
        resources: # setting resources info 
          requests:
            cpu: 100m # 1 vcpu = 1000m 
            memory: 400M 
          limits: 
            cpu: 400m 
            memory: 900M 
status: {}
