apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-db
  name: ashu-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-db
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        env: # to pass env vairable and its vaules 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: # reading value from somewhere 
            secretKeyRef: # reading from secret 
              key: ashudbpass # key 
              name: ashu-db-password # name of secret  
        - name: MYSQL_DATABASE
          value: ashudb
        resources: {}
status: {}
