apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-ashu-role1
  namespace: ashu-project
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
