apiVersion: batch/v1
kind: Job
metadata:
  name: ashu-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: busybox
        command: ["sh", "-c", "echo Hello OpenShift && sleep 5"]